version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "8009:3306"
    container_name: bluebird_mysql
    volumes:
      - "./mysql/data:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: elmismo
      MYSQL_DATABASE: bluebird
      MYSQL_USER: bluebird
      MYSQL_PASSWORD: bluebird_

  apachephp7:
    depends_on:
      - db
    image: wp-bluebird:latest
    container_name: bluebird_php
    volumes:
      - "./app:/var/www/html/"
    ports:
      - "8000:80"
    restart: always